sudo: required
dist: trusty
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
# before_install: scripts/travis/before_install.sh
install: python setup.py install
script: python setup.py nosetests
